export type StructuredFilters = {
  cuisines: string[];
  price_max: number | null;
  independent_preferred: boolean;
  tourist_centre: boolean;
  near_public_transport: boolean;
  dog_friendly?: boolean;
  wifi?: boolean;
};

export function extractStructuredFilters(query: string): StructuredFilters {
  const qLower = query.toLowerCase();

  const cuisines: string[] = [];
  const knownCuisines: Array<[string, string]> = [
    ["poland", "polish"],
    ["polish", "polish"],
    ["polska", "polish"],
    ["polsk", "polish"],
    ["pierogi", "polish"],
    ["eastern european", "eastern_european"],
    ["eastern european", "polish"],
    ["russian", "russian"],
    ["ukrainian", "ukrainian"],
    ["france", "french"],
    ["french", "french"],
    ["fransk", "french"],
    ["franskt", "french"],
    ["bistro", "bistro"],
    ["brasserie", "bistro"],
    ["sweden", "swedish"],
    ["swedish", "swedish"],
    ["svensk", "swedish"],
    ["svenskt", "swedish"],
    ["svenska", "swedish"],
    ["husmanskost", "swedish"],
    ["scandinavia", "scandinavian"],
    ["scandinavian", "scandinavian"],
    ["skandinavisk", "scandinavian"],
    ["skandinaviskt", "scandinavian"],
    ["skandinaviska", "scandinavian"],
    ["italy", "italian"],
    ["italian", "italian"],
    ["italiensk", "italian"],
    ["italienska", "italian"],
    ["italienskt", "italian"],
    ["trattoria", "italian"],
    ["trattorias", "italian"],
    ["pizza", "pizza"],
    ["pizzeria", "pizza"],
    ["pizzerior", "pizza"],
    ["pizzeriorna", "pizza"],
    ["pizzaställe", "pizza"],
    ["pizzaställen", "pizza"],
    ["sushi", "sushi"],
    ["japan", "japanese"],
    ["japanese", "japanese"],
    ["japansk", "japanese"],
    ["japanska", "japanese"],
    ["japanskt", "japanese"],
    ["izakaya", "japanese"],
    ["yakitori", "japanese"],
    ["germany", "german"],
    ["german", "german"],
    ["tysk", "german"],
    ["tyskt", "german"],
    ["tyska", "german"],
    ["austria", "austrian"],
    ["austrian", "austrian"],
    ["hungary", "hungarian"],
    ["hungarian", "hungarian"],
    ["goulash", "hungarian"],
    ["schnitzel", "schnitzel"],
    ["czech", "czech"],
    ["tjeckisk", "czech"],
    ["tjeckiskt", "czech"],
    ["tjeckiska", "czech"],
    ["tjeckien", "czech"],
    ["belgian", "belgian"],
    ["belgiskt", "belgian"],
    ["belgisk", "belgian"],
    ["belgiska", "belgian"],
    ["belgien", "belgian"],
    ["belgobaren", "belgian"],
    ["pub", "pub"],
    ["ölhus", "pub"],
    ["ölhall", "pub"],
    ["kvarterskrog", "pub"],
    ["thai", "thai"],
    ["thailand", "thai"],
    ["thailändsk", "thai"],
    ["thailändskt", "thai"],
    ["thaimat", "thai"],
    ["thaiställen", "thai"],
    ["thairestauranger", "thai"],
    ["thaimatställen", "thai"],
    ["indian", "indian"],
    ["india", "indian"],
    ["indisk", "indian"],
    ["indiska", "indian"],
    ["indiskt", "indian"],
    ["koreansk", "korean"],
    ["koreanska", "korean"],
    ["korean", "korean"],
    ["kinesisk", "chinese"],
    ["kinesiska", "chinese"],
    ["kinesiskt", "chinese"],
    ["chinese", "chinese"],
    ["kinaställen", "chinese"],
    ["kinaställe", "chinese"],
    ["kinastället", "chinese"],
    ["kinaställena", "chinese"],
    ["kinarestauranger", "chinese"],
    ["kinarestaurang", "chinese"],
    ["kinarestaurangen", "chinese"],
    ["kinarestaurangerna", "chinese"],
    ["kinakrogar", "chinese"],
    ["kinakrog", "chinese"],
    ["kinakrogen", "chinese"],
    ["kinakrogarna", "chinese"],
    ["kinamatställen", "chinese"],
    ["kinamatställe", "chinese"],
    ["kinamat", "chinese"],
    ["kinamaten", "chinese"],
    ["kina", "chinese"],
    ["china", "chinese"],
    ["sichuan", "chinese"],
    ["dim sum", "chinese"],
    ["dimsum", "chinese"],
    ["dumplings", "chinese"],
    ["dumpling", "chinese"],
    ["kantonesisk", "chinese"],
    ["kantonesiska", "chinese"],
    ["cantonese", "chinese"],
    ["vietnamesisk", "vietnamese"],
    ["vietnamesiska", "vietnamese"],
    ["vietnamese", "vietnamese"],
    ["coffee", "coffee"],
    ["kaffe", "coffee"],
    ["bakery", "bakery"],
    ["bageri", "bakery"],
    ["hantverksbageri", "bakery"],
    ["kardemummabulle", "bakery"],
    ["kardemumma", "bakery"],
    ["kanelbulle", "bakery"],
    ["kanelbullar", "bakery"],
    ["surdegsbröd", "bakery"],
    ["surdeg", "bakery"],
    ["burger", "burger"],
    ["burgers", "burger"],
    ["burgare", "burger"],
    ["burgaren", "burger"],
    ["burgarna", "burger"],
    ["hamburgare", "burger"],
    ["hamburgaren", "burger"],
    ["hamburgarna", "burger"],
    ["middle eastern", "middle_eastern"],
    ["mexican", "mexican"],
    ["mexikansk", "mexican"],
    ["mexikanska", "mexican"],
    ["mexico", "mexican"],
    ["tacos", "mexican"],
    ["tapas", "tapas"],
    ["tapas", "spanish"],
    ["spanish", "spanish"],
    ["spain", "spanish"],
    ["spansk", "spanish"],
    ["spanskt", "spanish"],
    ["paella", "spanish"],
    ["paella", "paella"],
    ["ramen", "ramen"],
  ];

  for (const [term, norm] of knownCuisines) {
    const matched = term === "pub"
      ? (/(?:^|[^a-zåäö])pub(s|ar|en)?(?:[^a-zåäö]|$)/i.test(qLower))
      : (term === "kina" || term === "china")
        ? (new RegExp(`(?:^|[^a-zåäö])${term}(?:[^a-zåäö]|$)`, "i").test(qLower))
        : qLower.includes(term);
    if (matched) {
      cuisines.push(norm);
    }
  }

  let priceMax: number | null = null;
  if (["not expensive", "budget", "affordable", "cheap", "cheaply", "moderate", "rimligt pris", "billigt", "prisvärt", "överkomligt"].some((kw) => qLower.includes(kw))) {
    priceMax = 250;
  } else if (["fine dining", "expensive", "upscale", "avsmakningsmeny", "tasting menu"].some((kw) => qLower.includes(kw))) {
    priceMax = 800;
  }

  const independentPreferred = ["family-run", "family run", "family-owned", "independent", "local", "authentic", "small business", "familjeägd", "familjeägt", "oberoende", "handgjorda", "handgjord", "hantverks", "artisan"].some(
    (kw) => qLower.includes(kw),
  );

  const touristCentre = !["outside", "away from", "outer", "suburb", "outside the tourist centre", "not in center"].some(
    (kw) => qLower.includes(kw),
  );

  const nearPublicTransport = ["public transport", "metro", "tunnelbana", "station", "bus", "transit", "train"].some(
    (kw) => qLower.includes(kw),
  );

  const dogFriendly = ["dog", "dogs", "hund", "hundar", "hundvänlig", "hundvänligt", "tasstipset", "dog-friendly"].some(
    (kw) => qLower.includes(kw),
  );
  const wifi = ["wifi", "wi-fi", "wi fi", "wireless internet", "free internet", "free wifi", "trådlöst internet", "trådlöst nätverk"].some(
    (kw) => qLower.includes(kw),
  );

  return {
    cuisines: [...new Set(cuisines)],
    price_max: priceMax,
    independent_preferred: independentPreferred,
    tourist_centre: touristCentre,
    near_public_transport: nearPublicTransport,
    dog_friendly: dogFriendly,
    wifi,
  };
}

export const CUISINE_ALIASES: Record<string, string[]> = {
  poland: ["polish", "poland", "polska", "polsk", "pierogi", "eastern_european", "eastern european"],
  polish: ["polish", "poland", "polska", "polsk", "pierogi", "eastern_european", "eastern european"],
  polska: ["polish", "poland", "polska", "polsk", "pierogi", "eastern_european", "eastern european"],
  polsk: ["polish", "poland", "polska", "polsk", "pierogi", "eastern_european"],
  pierogi: ["polish", "poland", "polska", "polsk", "pierogi", "eastern_european"],
  sweden: ["swedish", "sweden", "svensk", "husmanskost"],
  swedish: ["swedish", "sweden", "svensk", "husmanskost"],
  svensk: ["swedish", "sweden", "svensk", "husmanskost"],
  husmanskost: ["swedish", "husmanskost", "svensk"],
  italy: ["italian", "italy", "italiensk", "italienska", "pasta", "pizza", "trattoria"],
  italian: ["italian", "italy", "italiensk", "italienska", "pasta", "pizza", "trattoria"],
  italiensk: ["italian", "italy", "italiensk", "italienska", "pasta", "pizza", "trattoria"],
  italienska: ["italian", "italy", "italiensk", "italienska", "pasta", "pizza", "trattoria"],
  trattoria: ["italian", "trattoria", "trattorias", "pasta", "pizza"],
  trattorias: ["italian", "trattoria", "trattorias", "pasta", "pizza"],
  pizza: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  pizzeria: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  pizzerior: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  pizzeriorna: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  pizzastalle: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  pizzastallen: ["pizza", "pizzeria", "pizzerior", "pizzeriorna", "pizzastalle", "pizzastallen"],
  japan: ["japanese", "japan", "japansk", "japanska", "sushi", "ramen", "izakaya", "yakitori"],
  japanese: ["japanese", "japan", "japansk", "japanska", "sushi", "ramen", "izakaya", "yakitori"],
  japansk: ["japanese", "japan", "japansk", "japanska", "sushi", "ramen", "izakaya", "yakitori"],
  japanska: ["japanese", "japan", "japansk", "japanska", "sushi", "ramen", "izakaya", "yakitori"],
  izakaya: ["japanese", "japan", "izakaya", "yakitori"],
  yakitori: ["japanese", "japan", "izakaya", "yakitori"],
  mexico: ["mexican", "mexico", "mexikansk", "mexikanska", "tacos"],
  mexican: ["mexican", "mexico", "mexikansk", "mexikanska", "tacos"],
  mexikansk: ["mexican", "mexico", "mexikansk", "mexikanska", "tacos"],
  mexikanska: ["mexican", "mexico", "mexikansk", "mexikanska", "tacos"],
  tacos: ["mexican", "mexico", "mexikansk", "mexikanska", "tacos"],
  germany: ["german", "germany", "tysk", "tyskt", "tyska", "schnitzel", "austrian"],
  german: ["german", "germany", "tysk", "tyskt", "tyska", "schnitzel", "austrian"],
  austria: ["austrian", "austria", "schnitzel", "german"],
  austrian: ["austrian", "austria", "schnitzel", "german"],
  schnitzel: ["schnitzel", "german", "austrian", "czech", "tjeckisk", "tjeckiskt"],
  czech: ["czech", "tjeckisk", "tjeckiskt", "tjeckiska", "tjeckien", "schnitzel", "pub"],
  tjeckisk: ["czech", "tjeckisk", "tjeckiskt", "tjeckiska", "tjeckien", "schnitzel", "pub"],
  tjeckiskt: ["czech", "tjeckisk", "tjeckiskt", "tjeckiska", "tjeckien", "schnitzel", "pub"],
  tjeckiska: ["czech", "tjeckisk", "tjeckiskt", "tjeckiska", "tjeckien", "schnitzel", "pub"],
  tjeckien: ["czech", "tjeckisk", "tjeckiskt", "tjeckiska", "tjeckien", "schnitzel", "pub"],
  pub: ["pub", "ölhus", "ölhall", "kvarterskrog", "bar", "czech"],
  ölhus: ["pub", "ölhus", "ölhall", "czech", "german"],
  ölhall: ["pub", "ölhus", "ölhall", "czech", "german"],
  kvarterskrog: ["pub", "kvarterskrog", "ölhus", "czech"],
  french: ["french", "france", "fransk", "franskt", "bistro", "brasserie"],
  france: ["french", "france", "fransk", "franskt", "bistro", "brasserie"],
  fransk: ["french", "france", "fransk", "franskt", "bistro", "brasserie"],
  franskt: ["french", "france", "fransk", "franskt", "bistro", "brasserie"],
  belgian: ["belgian", "belgisk", "belgiskt", "belgiska", "belgien"],
  belgisk: ["belgian", "belgisk", "belgiskt", "belgiska", "belgien"],
  belgiskt: ["belgian", "belgisk", "belgiskt", "belgiska", "belgien"],
  belgiska: ["belgian", "belgisk", "belgiskt", "belgiska", "belgien"],
  belgien: ["belgian", "belgisk", "belgiskt", "belgiska", "belgien"],
  tysk: ["german", "germany", "tysk", "tyskt", "tyska", "schnitzel"],
  tyskt: ["german", "germany", "tysk", "tyskt", "tyska", "schnitzel"],
  tyska: ["german", "germany", "tysk", "tyskt", "tyska", "schnitzel"],
  bistro: ["bistro", "french", "fransk", "brasserie"],
  hungary: ["hungarian", "hungary", "goulash", "austrian"],
  hungarian: ["hungarian", "hungary", "goulash", "austrian"],
  goulash: ["goulash", "hungarian", "austrian"],
  spanish: ["spanish", "spain", "spansk", "spanskt", "paella", "tapas"],
  spain: ["spanish", "spain", "spansk", "spanskt", "paella", "tapas"],
  spansk: ["spanish", "spain", "spansk", "spanskt", "paella", "tapas"],
  spanskt: ["spanish", "spain", "spansk", "spanskt", "paella", "tapas"],
  paella: ["paella", "spanish", "spansk", "spanskt", "tapas"],
  tapas: ["tapas", "spanish", "spansk", "spanskt", "paella"],
  thai: ["thai", "thailand", "thailändsk", "thailändskt", "thaimat", "thaiställen", "thairestauranger"],
  thailändsk: ["thai", "thailand", "thailändsk", "thailändskt", "thaimat", "thaiställen", "thairestauranger"],
  indian: ["indian", "india", "indisk", "indiska", "indiskt"],
  indisk: ["indian", "india", "indisk", "indiska", "indiskt"],
  korean: ["korean", "koreansk", "koreanska"],
  koreansk: ["korean", "koreansk", "koreanska"],
  chinese: [
    "chinese", "kinesisk", "kinesiska", "kinesiskt",
    "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger",
    "kinakrog", "kinakrogar", "kinamat", "kinamatstalle", "kinamatstallen",
    "sichuan", "dim sum", "dimsum", "dumplings", "dumpling", "kantonesisk", "cantonese",
  ],
  kinesisk: [
    "chinese", "kinesisk", "kinesiska", "kinesiskt",
    "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger",
    "kinakrog", "kinakrogar", "kinamat", "kinamatstalle", "kinamatstallen",
    "sichuan", "dim sum", "dimsum", "dumplings", "dumpling", "kantonesisk", "cantonese",
  ],
  kina: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinastallet", "kinastallena", "kinarestaurang", "kinarestauranger", "kinarestaurangen", "kinarestaurangerna", "kinamat", "kinamaten"],
  kinastallen: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinastallet", "kinastallena", "kinarestaurang", "kinarestauranger", "kinamat"],
  kinastalle: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinastallet", "kinastallena", "kinarestaurang", "kinarestauranger", "kinamat"],
  kinastallet: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinastallet", "kinastallena", "kinarestaurang", "kinarestauranger", "kinamat"],
  kinastallena: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinastallet", "kinastallena", "kinarestaurang", "kinarestauranger", "kinamat"],
  kinarestaurang: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinarestaurangen", "kinarestaurangerna", "kinamat"],
  kinarestauranger: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinarestaurangen", "kinarestaurangerna", "kinamat"],
  kinarestaurangen: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinarestaurangen", "kinarestaurangerna", "kinamat"],
  kinarestaurangerna: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinarestaurangen", "kinarestaurangerna", "kinamat"],
  kinakrog: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinakrog", "kinakrogar", "kinakrogen", "kinakrogarna"],
  kinakrogar: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinakrog", "kinakrogar", "kinakrogen", "kinakrogarna"],
  kinakrogen: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinakrog", "kinakrogar", "kinakrogen", "kinakrogarna"],
  kinakrogarna: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinakrog", "kinakrogar", "kinakrogen", "kinakrogarna"],
  kinamat: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinamat", "kinamaten"],
  kinamaten: ["chinese", "kinesisk", "kinesiska", "kinesiskt", "kina", "kinastallen", "kinastalle", "kinarestaurang", "kinarestauranger", "kinamat", "kinamaten"],
  sichuan: ["chinese", "sichuan", "kinesisk", "kinesiska"],
  dumplings: ["dumplings", "dumpling", "dim sum", "chinese", "asian"],
  dumpling: ["dumplings", "dumpling", "dim sum", "chinese", "asian"],
  "dim sum": ["dim sum", "dimsum", "dumplings", "chinese", "cantonese"],
  vietnamese: ["vietnamese", "vietnamesisk", "vietnamesiska"],
  vietnamesisk: ["vietnamese", "vietnamesisk", "vietnamesiska"],
  kardemummabulle: ["bakery", "cardamom", "kardemumma", "fika"],
  kardemumma: ["bakery", "cardamom", "kardemumma", "fika"],
  surdegsbröd: ["bakery", "sourdough", "surdeg", "bread"],
  surdeg: ["bakery", "sourdough", "surdeg", "bread"],
  sourdough: ["bakery", "sourdough", "surdeg", "bread"],
  kanelbulle: ["bakery", "cinnamon", "fika"],
  kanelbullar: ["bakery", "cinnamon", "fika"],
  burger: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  burgers: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  burgare: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  burgaren: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  burgarna: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  hamburgare: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  hamburgaren: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
  hamburgarna: ["burger", "burgers", "burgare", "burgaren", "burgarna", "hamburgare", "hamburgaren", "hamburgarna"],
};
