-- Cleaned & Verified D1 place_photos seed file
DELETE FROM place_photos;

INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-1488435763-1', 1488435763, 'https://upload.wikimedia.org/wikipedia/commons/9/93/Blockmakarens_hus%2C_k%C3%B6ket%2C_2002.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Blockmakarens_hus%2C_k%C3%B6ket%2C_2002.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'H-hus (Blockmakarens hus, köket, 2002)', 'Wikimedia Commons / Fredriksson, Göran H.');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-1488435763-2', 1488435763, 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Blockmakarens_hus%2C_rummet%2C_2002.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Blockmakarens_hus%2C_rummet%2C_2002.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'H-hus (Blockmakarens hus, rummet, 2002)', 'Wikimedia Commons / Fredriksson, Göran H.');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-238385895-1', 238385895, 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Bullen_Berglund.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Bullen_Berglund.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Bullens (Bullen Berglund)', 'Wikimedia Commons / Unknown photographer');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-587510854-1', 587510854, 'https://upload.wikimedia.org/wikipedia/commons/6/60/Kaffekoppen_and_Chokladkoppen.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Kaffekoppen_and_Chokladkoppen.jpg/960px-Kaffekoppen_and_Chokladkoppen.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Chokladkoppen (Kaffekoppen and Chokladkoppen)', 'Wikimedia Commons / Alisdair McDiarmid from Glasgow, United ');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-4173619663-2', 4173619663, 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Proserpine_by_Dante_Gabriel_Rossetti_%281878%2C_Christie%27s%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Proserpine_by_Dante_Gabriel_Rossetti_%281878%2C_Christie%27s%29.jpg/960px-Proserpine_by_Dante_Gabriel_Rossetti_%281878%2C_Christie%27s%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Da Dante (Proserpine by Dante Gabriel Rossetti (1878, Christ)', 'Wikimedia Commons / Dante Gabriel Rossetti');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-404474033-1', 404474033, 'https://upload.wikimedia.org/wikipedia/commons/c/c4/21gota.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/21gota.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Bigges (21gota)', 'Wikimedia Commons / Petter Hektor');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-1621738409-2', 1621738409, 'https://upload.wikimedia.org/wikipedia/commons/9/96/Angelo_de_Gubernatis.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Angelo_de_Gubernatis.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Angelos (Angelo de Gubernatis)', 'Wikimedia Commons / Gunnar Vidar Forssell');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-1939518288-2', 1939518288, 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Wood_tar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Wood_tar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Pino (Wood tar)', 'Wikimedia Commons / No machine-readable author provided. Prz');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-773823653-2', 773823653, 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Anders_Eldeman_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Anders_Eldeman_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Lasse i Parken (Anders Eldeman (cropped))', 'Wikimedia Commons / Frankie Fouganthin');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-525340868-1', 525340868, 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Nils_Eden.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Nils_Eden.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Eden (Nils Eden)', 'Wikimedia Commons / IMS');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-687942764-1', 687942764, 'https://upload.wikimedia.org/wikipedia/commons/3/34/CG_Hellqvist_och_maka_detail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/3/34/CG_Hellqvist_och_maka_detail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Maka Maka (CG Hellqvist och maka detail)', 'Wikimedia Commons / Carl Gustaf Hellqvist');
INSERT INTO place_photos (id, place_id, url, thumbnail_url, caption, credit) VALUES ('photo-1282124810-2', 1282124810, 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Tommy_Steele_1957.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Tommy_Steele_1957.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Tommy’s (Tommy Steele 1957)', 'Wikimedia Commons / Svenska Dagbladet. Ehnemark, Jan.');
