BEGIN TRANSACTION;
DELETE FROM score_snapshots;
DELETE FROM engagement_snapshots;
DELETE FROM rating_snapshots;
DELETE FROM specialty_coffee_attributes;
DELETE FROM establishment_tags;
DELETE FROM evidence_sources;
DELETE FROM establishments;
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (1, 'Drop Coffee', 'Specialty coffee', 'Mariatorget', 'Independent roastery with traceable, light-roasted coffee and hand brew options.', 2, NULL, NULL, 'independent', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (1, 'Own roastery');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (1, 'Filter');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (1, 'Single origin');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (1, 'Independent');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (1, 'Beans');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (1, 4.6, 930, 1200, 4.2, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (1, 4200, 1140, 720, 360, 210, 148, 54, 42, 112, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (1, 'official_site', 'Official site', NULL, 0.9, '2026-07-20T13:19:56.430Z', 'Seed evidence for Drop Coffee');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (1, 'specialist_guide', 'specialist guide', NULL, 0.9, '2026-07-08T13:19:56.430Z', 'Seed evidence for Drop Coffee');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (1, 'osm', 'OSM', NULL, 0.9, '2026-06-26T13:19:56.430Z', 'Seed evidence for Drop Coffee');
INSERT INTO specialty_coffee_attributes (establishment_id, specialty_verified, own_roastery, traceable_coffee, filter_coffee, espresso_based, rotating_roasters, single_origin, manual_brew_methods_json, decaf_available, beans_for_sale, verification_sources, updated_at) VALUES (1, 1, 1, 1, 1, 1, 0, 1, '["V60","Aeropress"]', 1, 1, 3, '2026-08-13T13:19:56.430Z');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (2, 'Johan & Nyström', 'Specialty coffee', 'Mariatorget', 'An early force in Sweden''s specialty coffee scene, with a broad brew menu.', 2, NULL, NULL, 'unknown', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (2, 'Roaster');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (2, 'Filter');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (2, 'Beans');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (2, 'Lunch');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (2, 4.4, 1500, 1800, 4.2, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (2, 9700, 2200, 1340, 510, 305, 214, 71, 48, 121, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (2, 'specialist_guide', 'Specialist guide', NULL, 0.9, '2026-07-06T13:19:56.430Z', 'Seed evidence for Johan & Nyström');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (2, 'osm', 'OSM', NULL, 0.9, '2026-06-24T13:19:56.430Z', 'Seed evidence for Johan & Nyström');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (2, 'official_site', 'official site', NULL, 0.9, '2026-06-12T13:19:56.430Z', 'Seed evidence for Johan & Nyström');
INSERT INTO specialty_coffee_attributes (establishment_id, specialty_verified, own_roastery, traceable_coffee, filter_coffee, espresso_based, rotating_roasters, single_origin, manual_brew_methods_json, decaf_available, beans_for_sale, verification_sources, updated_at) VALUES (2, 1, 1, 1, 1, 1, 0, 1, '["V60"]', 1, 1, 3, '2026-08-13T13:19:56.430Z');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (3, 'Café Pascal', 'Specialty coffee', 'Vasastan', 'Coffee-led café with bakery credentials and strong cross-category relevance.', 2, NULL, NULL, 'unknown', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (3, 'Filter');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (3, 'Bakery');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (3, 'Lunch');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (3, 'Work');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (3, 4.5, 2100, 2600, 4.2, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (3, 13200, 3100, 1720, 720, 380, 306, 96, 60, 190, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (3, 'editorial', 'Editorial guide', NULL, 0.7, '2026-06-09T13:19:56.430Z', 'Seed evidence for Café Pascal');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (3, 'osm', 'OSM', NULL, 0.7, '2026-05-28T13:19:56.430Z', 'Seed evidence for Café Pascal');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (3, 'official_site', 'official sources', NULL, 0.7, '2026-05-16T13:19:56.430Z', 'Seed evidence for Café Pascal');
INSERT INTO specialty_coffee_attributes (establishment_id, specialty_verified, own_roastery, traceable_coffee, filter_coffee, espresso_based, rotating_roasters, single_origin, manual_brew_methods_json, decaf_available, beans_for_sale, verification_sources, updated_at) VALUES (3, 1, 0, 1, 1, 1, 1, 1, '["Batch brew"]', 1, 0, 2, '2026-08-13T13:19:56.430Z');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (4, 'Lillebrors Bageri', 'Bakery', 'Vasastan', 'Small-format bakery singled out by independent food writers for cardamom buns and viennoiserie.', 2, NULL, NULL, 'independent', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (4, 'Cardamom bun');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (4, 'Independent');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (4, 'Takeaway');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (4, 'Breakfast');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (4, 4.8, 520, 610, 4.25, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (4, 2100, 860, 570, 260, 150, 118, 41, 36, 96, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (4, 'editorial', 'Independent editorial sources', NULL, 0.7, '2026-07-24T13:19:56.430Z', 'Seed evidence for Lillebrors Bageri');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (4, 'osm', 'OSM', NULL, 0.7, '2026-07-12T13:19:56.430Z', 'Seed evidence for Lillebrors Bageri');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (5, 'Svedjan Bageri', 'Bakery', 'Södermalm', 'Farm-rooted bakery using organic flour, known for bread, pastries and fika.', 2, NULL, NULL, 'independent', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (5, 'Organic flour');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (5, 'Fika');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (5, 'Independent');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (5, 'Bread');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (5, 4.7, 430, 540, 4.25, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (5, 1800, 760, 520, 230, 138, 104, 44, 30, 86, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (5, 'editorial', 'Visit Stockholm', NULL, 0.9, '2026-07-28T13:19:56.430Z', 'Seed evidence for Svedjan Bageri');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (5, 'editorial', 'editorial sources', NULL, 0.9, '2026-07-16T13:19:56.430Z', 'Seed evidence for Svedjan Bageri');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (5, 'osm', 'OSM', NULL, 0.9, '2026-07-04T13:19:56.430Z', 'Seed evidence for Svedjan Bageri');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (6, 'Vete-Katten', 'Café', 'Norrmalm', 'Historic Stockholm pastry café; significant through longevity and cultural relevance.', 2, NULL, NULL, 'unknown', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (6, 'Classic');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (6, 'Patisserie');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (6, 'Since 1928');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (6, 'Fika');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (6, 4.3, 7800, 9400, 4.05, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (6, 28000, 6100, 3600, 920, 670, 530, 120, 88, 150, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (6, 'official_site', 'Official/history sources', NULL, 0.9, '2026-04-15T13:19:56.430Z', 'Seed evidence for Vete-Katten');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (6, 'osm', 'OSM', NULL, 0.9, '2026-04-03T13:19:56.430Z', 'Seed evidence for Vete-Katten');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (7, 'Aira', 'Restaurant', 'Djurgården', 'Destination restaurant represented here as a high-quality, high-popularity reference point.', 4, NULL, NULL, 'unknown', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (7, 'Nordic');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (7, 'Destination');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (7, 'Fine dining');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (7, 'Dinner');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (7, 4.7, 740, 860, 4.15, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (7, 6500, 1780, 940, 330, 188, 91, 17, 25, 78, '2026-05-15T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (7, 'editorial', 'Editorial sources', NULL, 0.7, '2026-06-29T13:19:56.431Z', 'Seed evidence for Aira');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (7, 'osm', 'OSM', NULL, 0.7, '2026-06-17T13:19:56.431Z', 'Seed evidence for Aira');
INSERT INTO establishments (id, name, type, district, description, price_level, latitude, longitude, chain_status, osm_type, osm_id, created_at, updated_at) VALUES (8, 'Socker Sucker', 'Bakery', 'Vasastan', 'Modern patisserie with specialist craft signals and comparatively high discovery value.', 3, NULL, NULL, 'independent', NULL, NULL, '2026-08-13T13:19:56.430Z', '2026-08-13T13:19:56.430Z');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (8, 'Patisserie');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (8, 'Pastry');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (8, 'Independent');
INSERT INTO establishment_tags (establishment_id, tag) VALUES (8, 'Fika');
INSERT INTO rating_snapshots (establishment_id, rating_average, reliable_rating_count, review_count, category_mean_rating, captured_at) VALUES (8, 4.6, 190, 240, 4.25, '2026-08-13T13:19:56.430Z');
INSERT INTO engagement_snapshots (establishment_id, search_impressions, profile_views, map_marker_clicks, saves, direction_requests, confirmed_visits, repeat_visits, recommendations, recent_saves, window_started_at, window_ended_at) VALUES (8, 980, 420, 310, 140, 82, 57, 19, 24, 61, '2026-05-15T13:19:56.431Z', '2026-08-13T13:19:56.430Z');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (8, 'editorial', 'Independent editorial sources', NULL, 0.7, '2026-08-01T13:19:56.431Z', 'Seed evidence for Socker Sucker');
INSERT INTO evidence_sources (establishment_id, source_type, source_name, url, confidence, captured_at, summary) VALUES (8, 'osm', 'OSM', NULL, 0.7, '2026-07-20T13:19:56.431Z', 'Seed evidence for Socker Sucker');
COMMIT;
