"use client";

import { useMemo, useState } from "react";

type Place = { id:number; name:string; kind:"Specialty coffee"|"Bakery"|"Restaurant"|"Café"; area:string; note:string; tags:string[]; quality:number; popularity:number; discovery:number; confidence:"High"|"Medium"; x:number; y:number; evidence:string };

const places: Place[] = [
  {id:1,name:"Drop Coffee",kind:"Specialty coffee",area:"Mariatorget",note:"Independent roastery with traceable, light-roasted coffee and hand brew options.",tags:["Own roastery","Filter","Single origin"],quality:94,popularity:82,discovery:63,confidence:"High",x:43,y:70,evidence:"Official site · specialist guide · OSM"},
  {id:2,name:"Johan & Nyström",kind:"Specialty coffee",area:"Mariatorget",note:"An early force in Sweden’s specialty coffee scene, with a broad brew menu.",tags:["Roaster","Filter","Beans"],quality:90,popularity:89,discovery:48,confidence:"High",x:47,y:66,evidence:"Specialist guide · OSM · official site"},
  {id:3,name:"Café Pascal",kind:"Specialty coffee",area:"Vasastan",note:"Coffee-led café with bakery credentials and strong cross-category relevance.",tags:["Filter","Bakery","Lunch"],quality:91,popularity:86,discovery:58,confidence:"Medium",x:39,y:30,evidence:"Editorial guide · OSM · official sources"},
  {id:4,name:"Lillebrors Bageri",kind:"Bakery",area:"Vasastan",note:"Small-format bakery singled out by independent food writers for cardamom buns and viennoiserie.",tags:["Cardamom bun","Independent","Takeaway"],quality:93,popularity:72,discovery:84,confidence:"Medium",x:32,y:34,evidence:"Independent editorial sources · OSM"},
  {id:5,name:"Svedjan Bageri",kind:"Bakery",area:"Södermalm",note:"Farm-rooted bakery using organic flour, known for bread, pastries and fika.",tags:["Organic flour","Fika","Independent"],quality:92,popularity:76,discovery:79,confidence:"High",x:35,y:76,evidence:"Visit Stockholm · editorial sources · OSM"},
  {id:6,name:"Vete-Katten",kind:"Café",area:"Norrmalm",note:"Historic Stockholm pastry café; significant through longevity and cultural relevance.",tags:["Classic","Patisserie","Since 1928"],quality:84,popularity:95,discovery:35,confidence:"High",x:49,y:39,evidence:"Official/history sources · OSM"},
  {id:7,name:"Aira",kind:"Restaurant",area:"Djurgården",note:"Destination restaurant represented here as a high-quality, high-popularity reference point.",tags:["Nordic","Destination","Fine dining"],quality:96,popularity:80,discovery:45,confidence:"Medium",x:78,y:55,evidence:"Editorial sources · OSM"},
  {id:8,name:"Socker Sucker",kind:"Bakery",area:"Vasastan",note:"Modern patisserie with specialist craft signals and comparatively high discovery value.",tags:["Patisserie","Pastry","Independent"],quality:88,popularity:57,discovery:88,confidence:"Medium",x:47,y:25,evidence:"Independent editorial sources · OSM"},
];
const modes=["For you","Hidden gems","Popular now","Quality first"] as const; type Mode=typeof modes[number];
function score(p:Place,m:Mode){if(m==="Hidden gems")return Math.round(p.quality*.45+p.discovery*.45+p.popularity*.1);if(m==="Popular now")return Math.round(p.popularity*.55+p.quality*.3+p.discovery*.15);if(m==="Quality first")return Math.round(p.quality*.65+p.popularity*.2+p.discovery*.15);return Math.round(p.quality*.4+p.popularity*.2+p.discovery*.3+8)}

export default function Home(){
 const[mode,setMode]=useState<Mode>("For you"),[kind,setKind]=useState("All places"),[query,setQuery]=useState(""),[selected,setSelected]=useState(1),[concierge,setConcierge]=useState("specialty coffee and a cardamom bun, away from the busiest tourist streets"),[answer,setAnswer]=useState<string|null>(null);
 const ranked=useMemo(()=>places.filter(p=>kind==="All places"||p.kind===kind).filter(p=>`${p.name} ${p.area} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>score(b,mode)-score(a,mode)),[mode,kind,query]);
 const active=places.find(p=>p.id===selected)??ranked[0]??places[0];
 function ask(){const q=concierge.toLowerCase(),coffee=q.includes("coffee")||q.includes("kaffe"),bakery=q.includes("bun")||q.includes("bager")||q.includes("pastr");const hidden=(items:Place[])=>items.sort((a,b)=>score(b,"Hidden gems")-score(a,"Hidden gems"))[0];let picks:Place[]=[];if(coffee)picks.push(hidden(places.filter(p=>p.kind==="Specialty coffee")));if(bakery)picks.push(hidden(places.filter(p=>p.kind==="Bakery")));if(!picks.length)picks=[...places].sort((a,b)=>score(b,"For you")-score(a,"For you")).slice(0,2);picks=[...new Map(picks.map(p=>[p.id,p])).values()];setAnswer(`${picks.map(p=>p.name).join(" + ")} best matches this demo query. The result prioritises verified craft signals and discovery value, while popularity contributes only 10%. Check current hours before travelling.`)}
 return <main>
  <header className="topbar"><a className="brand" href="#"><span>STHLM</span><b>OPEN TABLE</b></a><nav><a href="#map">Explore</a><a href="#method">Method</a><a href="#concierge">Concierge</a></nav><a className="about" href="#sources">About the data ↗</a></header>
  <section className="intro"><div><p className="eyebrow">Independent food discovery · Proof of concept</p><h1>Good places,<br/><i>not paid places.</i></h1></div><p className="lede">A transparent Stockholm map for restaurants, bakeries, cafés and specialty coffee. Popularity matters—but it never gets the final word.</p></section>
  <section className="controls" id="map"><label className="search"><span>⌕</span><input aria-label="Search places" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search place, area or feature"/></label><div className="chips">{["All places","Restaurant","Bakery","Café","Specialty coffee"].map(item=><button key={item} className={kind===item?"active":""} onClick={()=>setKind(item)}>{item}</button>)}</div></section>
  <section className="workspace"><div className="map-panel"><div className="map-grid"><div className="water water-one"/><div className="water water-two"/><span className="district d1">VASASTAN</span><span className="district d2">NORRMALM</span><span className="district d3">SÖDERMALM</span><span className="district d4">DJURGÅRDEN</span>{ranked.map((p,i)=><button aria-label={`Select ${p.name}`} key={p.id} onClick={()=>setSelected(p.id)} className={`pin ${p.id===active.id?"selected":""} kind-${p.kind.replaceAll(" ","-").toLowerCase()}`} style={{left:`${p.x}%`,top:`${p.y}%`}}><span>{i+1}</span></button>)}<div className="legend"><span><i className="dot coffee"/> Specialty</span><span><i className="dot bakery"/> Bakery</span><span><i className="dot food"/> Food</span></div></div>
   <article className="map-card"><p>{active.kind} · {active.area}</p><h2>{active.name}</h2><p className="note">{active.note}</p><div className="tag-row">{active.tags.map(t=><span key={t}>{t}</span>)}</div><div className="score-row"><div><b>{active.quality}</b><span>Quality</span></div><div><b>{active.popularity}</b><span>Popularity</span></div><div><b>{active.discovery}</b><span>Discovery</span></div></div><small>{active.confidence} confidence · {active.evidence}</small></article></div>
   <aside className="results"><div className="results-head"><div><p className="eyebrow">Transparent ranking</p><h2>{ranked.length} places in view</h2></div><select value={mode} onChange={e=>setMode(e.target.value as Mode)}>{modes.map(m=><option key={m}>{m}</option>)}</select></div><p className="formula">{mode==="Hidden gems"?"45% quality + 45% discovery + 10% popularity":mode==="Popular now"?"55% popularity + 30% quality + 15% discovery":mode==="Quality first"?"65% quality + 20% popularity + 15% discovery":"40% quality + 30% discovery + 20% popularity + match"}</p><div className="list">{ranked.map((p,i)=><button key={p.id} className={p.id===active.id?"place active-place":"place"} onClick={()=>setSelected(p.id)}><span className="rank">{String(i+1).padStart(2,"0")}</span><span className="place-main"><small>{p.kind} · {p.area}</small><strong>{p.name}</strong><span>{p.tags.slice(0,2).join(" · ")}</span></span><span className="total"><b>{score(p,mode)}</b><small>match</small></span></button>)}</div></aside></section>
  <section className="concierge" id="concierge"><div><p className="eyebrow">The independent concierge</p><h2>Tell us what <i>good</i><br/>means today.</h2><p>It searches the evidence first, then explains the recommendation. No invented opening hours. No paid placement.</p></div><div className="ask-box"><label htmlFor="ask">I’m looking for…</label><textarea id="ask" value={concierge} onChange={e=>setConcierge(e.target.value)}/><button onClick={ask}>Find my places <span>→</span></button>{answer&&<p className="answer">{answer}</p>}</div></section>
  <section className="inspiration"><p className="eyebrow">Research inspiration · Lauren Leek</p><blockquote>“Google Maps is not a directory. It’s a market maker.”</blockquote><div><p>Leek’s London work reframes ranked maps as attention allocators: visibility creates visits, visits create reviews, and reviews create more visibility.</p><p>Our Stockholm extension broadens that enquiry to bakeries, cafés and specialty coffee, then separates <b>quality</b>, <b>popularity</b> and <b>algorithmic surprise</b> instead of collapsing them into one star.</p></div></section>
  <section className="method" id="method"><div><p className="eyebrow">Open method · visible trade-offs</p><h2>Popularity is evidence.<br/>Not authority.</h2></div><div className="method-grid"><article><b>01</b><h3>Open baseline</h3><p>OSM and public registers establish what exists—not what an ad platform chooses to show.</p></article><article><b>02</b><h3>Plural quality</h3><p>Specialist guides, editorial sources and verified attributes build evidence across sources.</p></article><article><b>03</b><h3>Corrected popularity</h3><p>Bayesian weighting, recency and exposure correction stop review volume from taking over.</p></article><article><b>04</b><h3>Residual discovery</h3><p>Following Leek, a positive model residual marks places outperforming the platform baseline—not objective food quality.</p></article></div><div className="disclaimer" id="sources">POC DATA NOTE <span>This prototype uses a small hand-assembled demonstration set. Scores are illustrative—not published ratings. Production data must be licensed, refreshed and source-audited.</span></div><div className="source-links"><a href="https://laurenleek.substack.com/p/how-google-maps-quietly-allocates" target="_blank">Lauren Leek’s research ↗</a><a href="https://github.com/laurencleek/open_food_map" target="_blank">Open Food Map code ↗</a><a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap attribution ↗</a></div></section>
  <footer><span>STHLM OPEN TABLE / POC 01</span><span>OPEN DATA · OPEN METHOD · OPEN CITY</span></footer>
 </main>
}
