import type { PlaceInput } from "./scoring.ts";
import { addLocalPopularityPercentiles } from "./scoring.ts";

const evidence = {
  high: {
    specialistGuide: 1,
    independentEditorial: 1,
    verifiedUserRating: 1,
    repeatVisits: 82,
    recentReviews: 84,
    credibleReviewers: 78,
    inspectionStatus: 96,
    verifiedAttributes: 90,
    dataFreshness: 86,
    confidence: "High" as const,
  },
  medium: {
    specialistGuide: 0.6,
    independentEditorial: 1,
    verifiedUserRating: 0.8,
    repeatVisits: 64,
    recentReviews: 72,
    credibleReviewers: 68,
    inspectionStatus: 92,
    verifiedAttributes: 74,
    dataFreshness: 78,
    confidence: "Medium" as const,
  },
};

export const demoPlaces = addLocalPopularityPercentiles<PlaceInput>([
  {
    id: 1,
    name: "Drop Coffee",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Mariatorget",
    note: "Independent roastery with traceable, light-roasted coffee and hand brew options.",
    tags: ["Own roastery", "Filter", "Single origin", "Independent", "Beans"],
    evidenceLabel: "Official site · specialist guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 930,
    reviewCount: 1200,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.84,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 68,
    ageDays: 5600,
    daysSinceFreshEvidence: 24,
    evidence: evidence.high,
    engagement: {
      searchImpressions: 4200,
      profileViews: 1140,
      mapMarkerClicks: 720,
      saves: 360,
      directionRequests: 210,
      confirmedVisits: 148,
      repeatVisits: 54,
      recommendations: 42,
      recentSaves: 112,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Aeropress"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 43,
    y: 70,
  },
  {
    id: 2,
    name: "Johan & Nyström",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Mariatorget",
    note: "An early force in Sweden's specialty coffee scene, with a broad brew menu.",
    tags: ["Roaster", "Filter", "Beans", "Lunch"],
    evidenceLabel: "Specialist guide · OSM · official site",
    ratingAverage: 4.4,
    reliableRatingCount: 1500,
    reviewCount: 1800,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.91,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 82,
    ageDays: 5900,
    daysSinceFreshEvidence: 38,
    evidence: evidence.high,
    engagement: {
      searchImpressions: 9700,
      profileViews: 2200,
      mapMarkerClicks: 1340,
      saves: 510,
      directionRequests: 305,
      confirmedVisits: 214,
      repeatVisits: 71,
      recommendations: 48,
      recentSaves: 121,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 47,
    y: 66,
  },
  {
    id: 3,
    name: "Café Pascal",
    kind: "Specialty coffee",
    cuisine: "coffee;bakery",
    area: "Vasastan",
    note: "Coffee-led café with bakery credentials and strong cross-category relevance.",
    tags: ["Filter", "Bakery", "Lunch", "Work"],
    evidenceLabel: "Editorial guide · OSM · official sources",
    ratingAverage: 4.5,
    reliableRatingCount: 2100,
    reviewCount: 2600,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.9,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 88,
    ageDays: 4300,
    daysSinceFreshEvidence: 65,
    evidence: evidence.medium,
    engagement: {
      searchImpressions: 13200,
      profileViews: 3100,
      mapMarkerClicks: 1720,
      saves: 720,
      directionRequests: 380,
      confirmedVisits: 306,
      repeatVisits: 96,
      recommendations: 60,
      recentSaves: 190,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["Batch brew"],
      decafAvailable: true,
      beansForSale: false,
      verificationSources: 2,
    },
    x: 39,
    y: 30,
  },
  {
    id: 4,
    name: "Lillebrors Bageri",
    kind: "Bakery",
    cuisine: "bakery",
    area: "Vasastan",
    note: "Small-format bakery singled out by independent food writers for cardamom buns and viennoiserie.",
    tags: ["Cardamom bun", "Independent", "Takeaway", "Breakfast"],
    evidenceLabel: "Independent editorial sources · OSM",
    ratingAverage: 4.8,
    reliableRatingCount: 520,
    reviewCount: 610,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.72,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 42,
    ageDays: 2300,
    daysSinceFreshEvidence: 20,
    evidence: evidence.medium,
    engagement: {
      searchImpressions: 2100,
      profileViews: 860,
      mapMarkerClicks: 570,
      saves: 260,
      directionRequests: 150,
      confirmedVisits: 118,
      repeatVisits: 41,
      recommendations: 36,
      recentSaves: 96,
    },
    x: 32,
    y: 34,
  },
  {
    id: 5,
    name: "Svedjan Bageri",
    kind: "Bakery",
    cuisine: "bakery",
    area: "Södermalm",
    note: "Farm-rooted bakery using organic flour, known for bread, pastries and fika.",
    tags: ["Organic flour", "Fika", "Independent", "Bread"],
    evidenceLabel: "Visit Stockholm · editorial sources · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 430,
    reviewCount: 540,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.76,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 46,
    ageDays: 1300,
    daysSinceFreshEvidence: 16,
    evidence: evidence.high,
    engagement: {
      searchImpressions: 1800,
      profileViews: 760,
      mapMarkerClicks: 520,
      saves: 230,
      directionRequests: 138,
      confirmedVisits: 104,
      repeatVisits: 44,
      recommendations: 30,
      recentSaves: 86,
    },
    x: 35,
    y: 76,
  },
  {
    id: 6,
    name: "Vete-Katten",
    kind: "Café",
    cuisine: "patisserie;café",
    area: "Norrmalm",
    note: "Historic Stockholm pastry café; significant through longevity and cultural relevance.",
    tags: ["Classic", "Patisserie", "Since 1928", "Fika"],
    evidenceLabel: "Official/history sources · OSM",
    ratingAverage: 4.3,
    reliableRatingCount: 7800,
    reviewCount: 9400,
    categoryMeanRating: 4.05,
    categoryPopularityRaw: 0.97,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 96,
    ageDays: 35000,
    daysSinceFreshEvidence: 120,
    evidence: evidence.high,
    engagement: {
      searchImpressions: 28000,
      profileViews: 6100,
      mapMarkerClicks: 3600,
      saves: 920,
      directionRequests: 670,
      confirmedVisits: 530,
      repeatVisits: 120,
      recommendations: 88,
      recentSaves: 150,
    },
    x: 49,
    y: 39,
  },
  {
    id: 7,
    name: "Aira",
    kind: "Restaurant",
    cuisine: "nordic",
    area: "Djurgården",
    note: "Destination restaurant represented here as a high-quality, high-popularity reference point.",
    tags: ["Nordic", "Destination", "Fine dining", "Dinner"],
    evidenceLabel: "Editorial sources · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 740,
    reviewCount: 860,
    categoryMeanRating: 4.15,
    categoryPopularityRaw: 0.82,
    localPopularityPercentile: 0,
    priceLevel: 4,
    mainstreamExposure: 78,
    ageDays: 2100,
    daysSinceFreshEvidence: 45,
    evidence: evidence.medium,
    engagement: {
      searchImpressions: 6500,
      profileViews: 1780,
      mapMarkerClicks: 940,
      saves: 330,
      directionRequests: 188,
      confirmedVisits: 91,
      repeatVisits: 17,
      recommendations: 25,
      recentSaves: 78,
    },
    x: 78,
    y: 55,
  },
  {
    id: 8,
    name: "Socker Sucker",
    kind: "Bakery",
    cuisine: "patisserie;pastry",
    area: "Vasastan",
    note: "Modern patisserie with specialist craft signals and comparatively high discovery value.",
    tags: ["Patisserie", "Pastry", "Independent", "Fika"],
    evidenceLabel: "Independent editorial sources · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 190,
    reviewCount: 240,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.57,
    localPopularityPercentile: 0,
    priceLevel: 3,
    mainstreamExposure: 28,
    ageDays: 1150,
    daysSinceFreshEvidence: 12,
    evidence: evidence.medium,
    engagement: {
      searchImpressions: 980,
      profileViews: 420,
      mapMarkerClicks: 310,
      saves: 140,
      directionRequests: 82,
      confirmedVisits: 57,
      repeatVisits: 19,
      recommendations: 24,
      recentSaves: 61,
    },
    x: 47,
    y: 25,
  },
]);
