import type { PlaceInput } from "./scoring.ts";
import { addLocalPopularityPercentiles } from "./scoring.ts";

const evidence = {
  high: {
    specialistGuide: 1,
    independentEditorial: 1,
    verifiedUserRating: 1,
    repeatVisits: 82,
    recentReviews: 84,
    credibleReviewers: 78,
    inspectionStatus: 96,
    verifiedAttributes: 90,
    dataFreshness: 86,
    confidence: "High" as const,
  },
  medium: {
    specialistGuide: 0.6,
    independentEditorial: 1,
    verifiedUserRating: 0.8,
    repeatVisits: 64,
    recentReviews: 72,
    credibleReviewers: 68,
    inspectionStatus: 92,
    verifiedAttributes: 74,
    dataFreshness: 78,
    confidence: "Medium" as const,
  },
};

export const demoPlaces = addLocalPopularityPercentiles<PlaceInput>([
  {
    id: 1,
    name: "Drop Coffee",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Mariatorget",
    address: "Wollmar Yxkullsgatan 10",
    note: "Independent roastery with traceable, light-roasted coffee and hand brew options.",
    tags: ["Own roastery", "Filter", "Single origin", "Independent", "Beans"],
    evidenceLabel: "Official site · specialist guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 930,
    reviewCount: 1200,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.84,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 68,
    ageDays: 5600,
    daysSinceFreshEvidence: 24,
    evidence: evidence.high,
    latitude: 59.3174,
    longitude: 18.062,
    engagement: {
      searchImpressions: 4200,
      profileViews: 1140,
      mapMarkerClicks: 720,
      saves: 360,
      directionRequests: 210,
      confirmedVisits: 148,
      repeatVisits: 54,
      recommendations: 42,
      recentSaves: 112,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Aeropress"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 43,
    y: 70,
  },
  {
    id: 2,
    name: "Johan & Nyström",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Mariatorget",
    address: "Swedenborgsgatan 7",
    note: "An early force in Sweden's specialty coffee scene, with a broad brew menu.",
    tags: ["Roaster", "Filter", "Beans", "Lunch"],
    evidenceLabel: "Specialist guide · OSM · official site",
    ratingAverage: 4.4,
    reliableRatingCount: 1500,
    reviewCount: 1800,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.91,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 82,
    ageDays: 5900,
    daysSinceFreshEvidence: 38,
    evidence: evidence.high,
    latitude: 59.3168,
    longitude: 18.0628,
    engagement: {
      searchImpressions: 9700,
      profileViews: 2200,
      mapMarkerClicks: 1340,
      saves: 510,
      directionRequests: 305,
      confirmedVisits: 214,
      repeatVisits: 71,
      recommendations: 48,
      recentSaves: 121,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 47,
    y: 66,
  },
  {
    id: 3,
    name: "Café Pascal (Norrtullsgatan)",
    kind: "Specialty coffee",
    cuisine: "coffee;bakery",
    area: "Vasastan",
    address: "Norrtullsgatan 4",
    note: "Acclaimed coffee-led café with in-house bakery credentials, rotating guest roasters and batch brew.",
    tags: ["Filter", "Bakery", "Cardamom bun", "Single origin", "Vasastan"],
    evidenceLabel: "Editorial guide · OSM · official sources",
    ratingAverage: 4.6,
    reliableRatingCount: 2100,
    reviewCount: 2600,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.9,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 82,
    ageDays: 4300,
    daysSinceFreshEvidence: 15,
    evidence: evidence.high,
    latitude: 59.3425,
    longitude: 18.0535,
    engagement: {
      searchImpressions: 13200,
      profileViews: 3100,
      mapMarkerClicks: 1720,
      saves: 720,
      directionRequests: 380,
      confirmedVisits: 306,
      repeatVisits: 96,
      recommendations: 60,
      recentSaves: 190,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["Batch brew", "V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 39,
    y: 30,
  },
  {
    id: 4,
    name: "Pascal Café & Bakery (Skånegatan)",
    kind: "Specialty coffee",
    cuisine: "coffee;bakery",
    area: "Södermalm",
    address: "Skånegatan 76",
    note: "Pascal's vibrant Södermalm outpost combining precision espresso, single origin brews, and fresh baking.",
    tags: ["Specialty coffee", "Bakery", "Cardamom bun", "Södermalm", "Filter"],
    evidenceLabel: "Independent editorial · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 890,
    reviewCount: 1120,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.85,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 64,
    ageDays: 2800,
    daysSinceFreshEvidence: 10,
    evidence: evidence.high,
    latitude: 59.313,
    longitude: 18.083,
    engagement: {
      searchImpressions: 5400,
      profileViews: 1420,
      mapMarkerClicks: 880,
      saves: 410,
      directionRequests: 230,
      confirmedVisits: 165,
      repeatVisits: 58,
      recommendations: 45,
      recentSaves: 130,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["Batch brew"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 62,
    y: 75,
  },
  {
    id: 5,
    name: "Pascal Kaffebar (Sturegatan)",
    kind: "Specialty coffee",
    cuisine: "coffee;bakery",
    area: "Östermalm",
    address: "Sturegatan 8",
    note: "Pascal's sleek Östermalm kaffebar serving hand-brewed single origins and viennoiserie.",
    tags: ["Specialty coffee", "Filter", "Single origin", "Östermalm", "Bakery"],
    evidenceLabel: "Editorial guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 620,
    reviewCount: 780,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.8,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 60,
    ageDays: 1900,
    daysSinceFreshEvidence: 12,
    evidence: evidence.high,
    latitude: 59.3375,
    longitude: 18.0735,
    engagement: {
      searchImpressions: 4100,
      profileViews: 1100,
      mapMarkerClicks: 650,
      saves: 320,
      directionRequests: 180,
      confirmedVisits: 125,
      repeatVisits: 42,
      recommendations: 34,
      recentSaves: 95,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 58,
    y: 44,
  },
  {
    id: 6,
    name: "Solkant, Café & Roastery",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Kungsholmen",
    address: "Pipersgatan 24",
    note: "Independent micro-roastery and café on Kungsholmen dedicated to single origin roasts and pour-overs.",
    tags: ["Own roastery", "Kungsholmen", "Single origin", "Filter", "Beans"],
    evidenceLabel: "Specialist guide · verified roastery",
    ratingAverage: 4.7,
    reliableRatingCount: 340,
    reviewCount: 410,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.72,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 35,
    ageDays: 1200,
    daysSinceFreshEvidence: 8,
    evidence: evidence.high,
    latitude: 59.3305,
    longitude: 18.045,
    engagement: {
      searchImpressions: 2100,
      profileViews: 820,
      mapMarkerClicks: 510,
      saves: 270,
      directionRequests: 140,
      confirmedVisits: 98,
      repeatVisits: 40,
      recommendations: 32,
      recentSaves: 88,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Kalita Wave"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 28,
    y: 48,
  },
  {
    id: 7,
    name: "Volca Coffee Roaster",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Kungsholmen",
    address: "Hantverkargatan 8",
    note: "Craft coffee roaster with dedicated brew bar offering artisanal roasts and bean sales.",
    tags: ["Own roastery", "Brew bar", "Single origin", "Kungsholmen", "Beans"],
    evidenceLabel: "Specialist guide · verified roastery",
    ratingAverage: 4.8,
    reliableRatingCount: 290,
    reviewCount: 350,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.68,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 30,
    ageDays: 950,
    daysSinceFreshEvidence: 6,
    evidence: evidence.high,
    latitude: 59.3281,
    longitude: 18.0465,
    engagement: {
      searchImpressions: 1850,
      profileViews: 740,
      mapMarkerClicks: 460,
      saves: 240,
      directionRequests: 125,
      confirmedVisits: 85,
      repeatVisits: 36,
      recommendations: 29,
      recentSaves: 82,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Aeropress"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 30,
    y: 53,
  },
  {
    id: 8,
    name: "Höga Kusten Kaffe Rosteri",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Kungsholmen",
    address: "Fleminggatan 53",
    note: "Nordic specialty roastery outpost featuring Northern Swedish roasted beans and precision brews.",
    tags: ["Own roastery", "Nordic roast", "Kungsholmen", "Filter", "Beans"],
    evidenceLabel: "Verified roastery · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 210,
    reviewCount: 260,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.62,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 25,
    ageDays: 800,
    daysSinceFreshEvidence: 14,
    evidence: evidence.high,
    latitude: 59.334,
    longitude: 18.034,
    engagement: {
      searchImpressions: 1420,
      profileViews: 580,
      mapMarkerClicks: 370,
      saves: 190,
      directionRequests: 98,
      confirmedVisits: 64,
      repeatVisits: 28,
      recommendations: 22,
      recentSaves: 68,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 21,
    y: 42,
  },
  {
    id: 9,
    name: "Muttley & Jack's Coffee Roasters",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Södermalm",
    address: "Barnängsgatan 13",
    note: "Award-winning specialty roastery renowned for micro-lot coffees and international roaster competitions.",
    tags: ["Own roastery", "Micro-lot", "Single origin", "Filter", "Beans"],
    evidenceLabel: "Specialist guide · roaster awards · OSM",
    ratingAverage: 4.8,
    reliableRatingCount: 420,
    reviewCount: 510,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.75,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 38,
    ageDays: 2400,
    daysSinceFreshEvidence: 5,
    evidence: evidence.high,
    latitude: 59.3105,
    longitude: 18.093,
    engagement: {
      searchImpressions: 3100,
      profileViews: 1050,
      mapMarkerClicks: 640,
      saves: 340,
      directionRequests: 175,
      confirmedVisits: 118,
      repeatVisits: 46,
      recommendations: 38,
      recentSaves: 105,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Aeropress", "Batch brew"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 70,
    y: 80,
  },
  {
    id: 10,
    name: "Standout Coffee",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Östermalm",
    address: "Frihamnsgatan 23",
    note: "World-class specialty coffee roaster focusing on rare varieties, competition roasts, and subscription beans.",
    tags: ["Own roastery", "Competition coffee", "Rare varieties", "Filter", "Beans"],
    evidenceLabel: "World Coffee Events · specialist guide · official site",
    ratingAverage: 4.9,
    reliableRatingCount: 380,
    reviewCount: 460,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.78,
    localPopularityPercentile: 0,
    priceLevel: 3,
    mainstreamExposure: 32,
    ageDays: 1600,
    daysSinceFreshEvidence: 4,
    evidence: evidence.high,
    latitude: 59.348,
    longitude: 18.117,
    engagement: {
      searchImpressions: 2800,
      profileViews: 980,
      mapMarkerClicks: 590,
      saves: 310,
      directionRequests: 160,
      confirmedVisits: 102,
      repeatVisits: 44,
      recommendations: 36,
      recentSaves: 98,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Origami", "Chemex"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 82,
    y: 22,
  },
  {
    id: 11,
    name: "Lykke",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Södermalm",
    address: "Nytorgsgatan 38",
    note: "Playful specialty coffee roastery with direct-farm ownership and vibrant brew bar on Nytorget.",
    tags: ["Own roastery", "Direct trade", "Single origin", "Nytorget", "Beans"],
    evidenceLabel: "Specialist guide · official site · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 1100,
    reviewCount: 1400,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.88,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 72,
    ageDays: 2100,
    daysSinceFreshEvidence: 9,
    evidence: evidence.high,
    latitude: 59.3135,
    longitude: 18.0805,
    engagement: {
      searchImpressions: 8900,
      profileViews: 2100,
      mapMarkerClicks: 1250,
      saves: 480,
      directionRequests: 280,
      confirmedVisits: 195,
      repeatVisits: 68,
      recommendations: 44,
      recentSaves: 115,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: true,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: false,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Batch brew"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 60,
    y: 74,
  },
  {
    id: 12,
    name: "Gast",
    kind: "Specialty coffee",
    cuisine: "coffee;café",
    area: "Vasastan",
    address: "Rådmansgatan 57",
    note: "Coffee-driven café in Vasastan known for curated guest roasters, espresso precision, and fresh brunch.",
    tags: ["Guest roasters", "Filter", "Vasastan", "Brunch", "Single origin"],
    evidenceLabel: "Editorial guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 820,
    reviewCount: 980,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.83,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 65,
    ageDays: 2600,
    daysSinceFreshEvidence: 18,
    evidence: evidence.high,
    latitude: 59.3408,
    longitude: 18.056,
    engagement: {
      searchImpressions: 5800,
      profileViews: 1490,
      mapMarkerClicks: 890,
      saves: 390,
      directionRequests: 215,
      confirmedVisits: 148,
      repeatVisits: 52,
      recommendations: 39,
      recentSaves: 108,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["Batch brew", "V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 41,
    y: 33,
  },
  {
    id: 13,
    name: "Nordic Brew Lab Stockholm",
    kind: "Specialty coffee",
    cuisine: "coffee",
    area: "Vasastan",
    address: "Torsgatan 46",
    note: "Experimental specialty brew bar highlighting Nordic roast profiles, batch brews, and single origins.",
    tags: ["Brew lab", "Nordic roast", "Single origin", "Vasastan", "Filter"],
    evidenceLabel: "Specialist guide · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 240,
    reviewCount: 310,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.64,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 28,
    ageDays: 750,
    daysSinceFreshEvidence: 7,
    evidence: evidence.high,
    latitude: 59.3435,
    longitude: 18.036,
    engagement: {
      searchImpressions: 1650,
      profileViews: 680,
      mapMarkerClicks: 410,
      saves: 210,
      directionRequests: 110,
      confirmedVisits: 72,
      repeatVisits: 31,
      recommendations: 26,
      recentSaves: 74,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["V60", "Aeropress"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 25,
    y: 28,
  },
  {
    id: 14,
    name: "A.B.Café",
    kind: "Specialty coffee",
    cuisine: "coffee;café",
    area: "Hägersten",
    address: "Valborgsmässovägen 34",
    note: "Charming neighborhood specialty café in Telefonplan / Hägersten serving specialty coffee and homemade baking.",
    tags: ["Specialty coffee", "Hägersten", "Independent", "Filter", "Bakery"],
    evidenceLabel: "Editorial guide · local choice · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 480,
    reviewCount: 590,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.74,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 34,
    ageDays: 3100,
    daysSinceFreshEvidence: 11,
    evidence: evidence.high,
    latitude: 59.3005,
    longitude: 18.001,
    engagement: {
      searchImpressions: 2900,
      profileViews: 920,
      mapMarkerClicks: 560,
      saves: 290,
      directionRequests: 145,
      confirmedVisits: 105,
      repeatVisits: 48,
      recommendations: 35,
      recentSaves: 92,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: true,
      verificationSources: 3,
    },
    x: 12,
    y: 90,
  },
  {
    id: 15,
    name: "Café Blom",
    kind: "Specialty coffee",
    cuisine: "coffee;café",
    area: "Skeppsholmen",
    address: "Exercisplan 2a",
    note: "Idyllic island café on Skeppsholmen serving specialty brews, pastries, and garden seating away from central noise.",
    tags: ["Specialty coffee", "Skeppsholmen", "Garden", "Filter", "Quiet"],
    evidenceLabel: "Editorial guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 360,
    reviewCount: 440,
    categoryMeanRating: 4.2,
    categoryPopularityRaw: 0.7,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 40,
    ageDays: 2200,
    daysSinceFreshEvidence: 16,
    evidence: evidence.high,
    latitude: 59.3262,
    longitude: 18.0845,
    engagement: {
      searchImpressions: 2400,
      profileViews: 810,
      mapMarkerClicks: 490,
      saves: 250,
      directionRequests: 130,
      confirmedVisits: 88,
      repeatVisits: 36,
      recommendations: 28,
      recentSaves: 79,
    },
    specialty: {
      specialtyVerified: true,
      ownRoastery: false,
      traceableCoffee: true,
      filterCoffee: true,
      espressoBased: true,
      rotatingRoasters: true,
      singleOrigin: true,
      manualBrewMethods: ["V60"],
      decafAvailable: true,
      beansForSale: false,
      verificationSources: 3,
    },
    x: 64,
    y: 58,
  },
  {
    id: 16,
    name: "Lillebrors Bageri",
    kind: "Bakery",
    cuisine: "bakery",
    area: "Vasastan",
    address: "Rörstrandsgatan 12",
    note: "Small-format bakery singled out by independent food writers for cardamom buns and viennoiserie.",
    tags: ["Cardamom bun", "Independent", "Takeaway", "Breakfast"],
    evidenceLabel: "Independent editorial sources · OSM",
    ratingAverage: 4.8,
    reliableRatingCount: 520,
    reviewCount: 610,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.72,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 42,
    ageDays: 2300,
    daysSinceFreshEvidence: 20,
    evidence: evidence.medium,
    latitude: 59.3395,
    longitude: 18.0345,
    engagement: {
      searchImpressions: 2100,
      profileViews: 860,
      mapMarkerClicks: 570,
      saves: 260,
      directionRequests: 150,
      confirmedVisits: 118,
      repeatVisits: 41,
      recommendations: 36,
      recentSaves: 96,
    },
    x: 32,
    y: 34,
  },
  {
    id: 17,
    name: "Svedjan Bageri",
    kind: "Bakery",
    cuisine: "bakery",
    area: "Södermalm",
    address: "Nytorgsgatan 24",
    note: "Farm-rooted bakery using organic flour, known for bread, pastries and fika.",
    tags: ["Organic flour", "Fika", "Independent", "Bread"],
    evidenceLabel: "Visit Stockholm · editorial sources · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 430,
    reviewCount: 540,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.76,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 46,
    ageDays: 1300,
    daysSinceFreshEvidence: 16,
    evidence: evidence.high,
    latitude: 59.3145,
    longitude: 18.0815,
    engagement: {
      searchImpressions: 1800,
      profileViews: 760,
      mapMarkerClicks: 520,
      saves: 230,
      directionRequests: 138,
      confirmedVisits: 104,
      repeatVisits: 44,
      recommendations: 30,
      recentSaves: 86,
    },
    x: 35,
    y: 76,
  },
  {
    id: 18,
    name: "Socker Sucker",
    kind: "Bakery",
    cuisine: "patisserie;pastry",
    area: "Vasastan",
    address: "Drottninggatan 93",
    note: "Modern patisserie with specialist craft signals and comparatively high discovery value.",
    tags: ["Patisserie", "Pastry", "Independent", "Fika"],
    evidenceLabel: "Independent editorial sources · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 190,
    reviewCount: 240,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.57,
    localPopularityPercentile: 0,
    priceLevel: 3,
    mainstreamExposure: 28,
    ageDays: 1150,
    daysSinceFreshEvidence: 12,
    evidence: evidence.medium,
    latitude: 59.338,
    longitude: 18.0575,
    engagement: {
      searchImpressions: 980,
      profileViews: 420,
      mapMarkerClicks: 310,
      saves: 140,
      directionRequests: 82,
      confirmedVisits: 57,
      repeatVisits: 19,
      recommendations: 24,
      recentSaves: 61,
    },
    x: 47,
    y: 25,
  },
  {
    id: 19,
    name: "800 Grader",
    kind: "Restaurant",
    cuisine: "pizza",
    area: "Vasastan",
    address: "Sigtunagatan 17",
    note: "Famous independent wood-fired sourdough pizza, organic local ingredients.",
    tags: ["Pizza", "Sourdough", "Independent", "Casual", "Wine"],
    evidenceLabel: "Independent editorial · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 890,
    reviewCount: 1100,
    categoryMeanRating: 4.3,
    categoryPopularityRaw: 0.82,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 62,
    ageDays: 3200,
    daysSinceFreshEvidence: 15,
    evidence: evidence.high,
    latitude: 59.3402,
    longitude: 18.0415,
    engagement: { searchImpressions: 3400, profileViews: 980, mapMarkerClicks: 610, saves: 420, directionRequests: 280, confirmedVisits: 190, repeatVisits: 85, recommendations: 72, recentSaves: 120 },
    x: 35,
    y: 18,
  },
  {
    id: 20,
    name: "Omnipollos Hatt",
    kind: "Restaurant",
    cuisine: "pizza",
    area: "Södermalm",
    address: "Hökens Gata 3",
    note: "Craft beer & sourdough pizza bar on Slussen hill, independent craft brewery concept.",
    tags: ["Pizza", "Craft beer", "Independent", "Sourdough", "Outdoor seating"],
    evidenceLabel: "Craft guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 1450,
    reviewCount: 1800,
    categoryMeanRating: 4.3,
    categoryPopularityRaw: 0.88,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 70,
    ageDays: 3800,
    daysSinceFreshEvidence: 8,
    evidence: evidence.high,
    latitude: 59.3179,
    longitude: 18.0722,
    engagement: { searchImpressions: 4800, profileViews: 1420, mapMarkerClicks: 890, saves: 510, directionRequests: 320, confirmedVisits: 240, repeatVisits: 110, recommendations: 95, recentSaves: 150 },
    x: 65,
    y: 72,
  },
  {
    id: 21,
    name: "Soldaten Svejk",
    kind: "Restaurant",
    cuisine: "schnitzel",
    area: "Södermalm",
    address: "Östgötagatan 35",
    note: "Legendary independent Czech restaurant famous for authentic pan-fried pork schnitzel and unpasteurized Czech pilsner.",
    tags: ["Schnitzel", "Czech", "Central European", "Independent", "Pub"],
    evidenceLabel: "Editorial guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 1600,
    reviewCount: 2100,
    categoryMeanRating: 4.35,
    categoryPopularityRaw: 0.86,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 65,
    ageDays: 9500,
    daysSinceFreshEvidence: 10,
    evidence: evidence.high,
    latitude: 59.3138,
    longitude: 18.0754,
    engagement: { searchImpressions: 5100, profileViews: 1580, mapMarkerClicks: 940, saves: 580, directionRequests: 390, confirmedVisits: 290, repeatVisits: 140, recommendations: 110, recentSaves: 180 },
    x: 68,
    y: 80,
  },
  {
    id: 22,
    name: "Lilla Prag",
    kind: "Restaurant",
    cuisine: "schnitzel",
    area: "Vasastan",
    address: "St Eriksplan 1",
    note: "Neighborhood Czech tavern serving authentic Viennese & Czech style crispy schnitzels.",
    tags: ["Schnitzel", "Central European", "Independent", "Tavern"],
    evidenceLabel: "Local guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 720,
    reviewCount: 950,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.75,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 55,
    ageDays: 4500,
    daysSinceFreshEvidence: 18,
    evidence: evidence.medium,
    latitude: 59.3395,
    longitude: 18.0382,
    engagement: { searchImpressions: 2200, profileViews: 680, mapMarkerClicks: 410, saves: 240, directionRequests: 160, confirmedVisits: 110, repeatVisits: 52, recommendations: 41, recentSaves: 75 },
    x: 32,
    y: 20,
  },
  {
    id: 23,
    name: "Flippin' Burgers",
    kind: "Restaurant",
    cuisine: "burger",
    area: "Vasastan",
    address: "Observatoriegatan 8",
    note: "Pioneer independent craft burger joint working exclusively with local Swedish meat producers.",
    tags: ["Burger", "Craft burger", "Independent", "Swedish meat"],
    evidenceLabel: "Specialist guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 2200,
    reviewCount: 3100,
    categoryMeanRating: 4.3,
    categoryPopularityRaw: 0.90,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 78,
    ageDays: 4800,
    daysSinceFreshEvidence: 14,
    evidence: evidence.high,
    latitude: 59.3391,
    longitude: 18.0512,
    engagement: { searchImpressions: 6200, profileViews: 1900, mapMarkerClicks: 1100, saves: 690, directionRequests: 450, confirmedVisits: 320, repeatVisits: 160, recommendations: 130, recentSaves: 210 },
    x: 42,
    y: 22,
  },
  {
    id: 24,
    name: "Pyza Polish Bistro",
    kind: "Restaurant",
    cuisine: "polish;eastern_european",
    area: "Södermalm",
    address: "Ringvägen 110",
    note: "Authentic independent Polish bistro specializing in handmade pierogi, barszcz, bigos, and classic Polish comfort food.",
    tags: ["Polish", "Eastern European", "Pierogi", "Family-run", "Independent"],
    evidenceLabel: "Specialist guide · Local audit",
    ratingAverage: 4.7,
    reliableRatingCount: 480,
    reviewCount: 610,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.82,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 42,
    ageDays: 1800,
    daysSinceFreshEvidence: 12,
    evidence: evidence.high,
    latitude: 59.3092,
    longitude: 18.0745,
    engagement: { searchImpressions: 2800, profileViews: 820, mapMarkerClicks: 510, saves: 310, directionRequests: 190, confirmedVisits: 140, repeatVisits: 75, recommendations: 55, recentSaves: 95 },
    x: 55,
    y: 72,
  },
  {
    id: 25,
    name: "Restaurang Babcia",
    kind: "Restaurant",
    cuisine: "polish;eastern_european",
    area: "Vasastan",
    address: "Torsgatan 48",
    note: "Homestyle Polish restaurant offering traditional pierogi, żurek, Polish dumplings, and authentic Central European hospitality.",
    tags: ["Polish", "Eastern European", "Pierogi", "Traditional", "Independent"],
    evidenceLabel: "Independent editorial · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 390,
    reviewCount: 480,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.78,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 38,
    ageDays: 1400,
    daysSinceFreshEvidence: 15,
    evidence: evidence.high,
    latitude: 59.3398,
    longitude: 18.0435,
    engagement: { searchImpressions: 2100, profileViews: 640, mapMarkerClicks: 390, saves: 230, directionRequests: 140, confirmedVisits: 98, repeatVisits: 48, recommendations: 38, recentSaves: 70 },
    x: 36,
    y: 21,
  },
  {
    id: 26,
    name: "La Neta",
    kind: "Restaurant",
    cuisine: "mexican",
    area: "Norrmalm",
    address: "Barnhusgatan 2",
    note: "Authentic independent Mexican taqueria serving fresh corn tortilla tacos, carnitas, al pastor, and homemade salsas.",
    tags: ["Mexican", "Tacos", "Taqueria", "Authentic", "Independent"],
    evidenceLabel: "Specialist guide · OSM",
    ratingAverage: 4.6,
    reliableRatingCount: 1800,
    reviewCount: 2400,
    categoryMeanRating: 4.3,
    categoryPopularityRaw: 0.88,
    localPopularityPercentile: 0,
    priceLevel: 1,
    mainstreamExposure: 65,
    ageDays: 3600,
    daysSinceFreshEvidence: 10,
    evidence: evidence.high,
    latitude: 59.3362,
    longitude: 18.0581,
    engagement: { searchImpressions: 5100, profileViews: 1600, mapMarkerClicks: 940, saves: 580, directionRequests: 390, confirmedVisits: 280, repeatVisits: 140, recommendations: 110, recentSaves: 180 },
    x: 48,
    y: 28,
  },
  {
    id: 27,
    name: "Cheibo Taqueria",
    kind: "Restaurant",
    cuisine: "mexican",
    area: "Södermalm",
    address: "Skånegatan 85",
    note: "Independent Mexican street food joint in Södermalm serving handmade tacos, birria, and authentic agave drinks.",
    tags: ["Mexican", "Tacos", "Street food", "Birria", "Independent"],
    evidenceLabel: "Local audit · OSM",
    ratingAverage: 4.7,
    reliableRatingCount: 520,
    reviewCount: 680,
    categoryMeanRating: 4.3,
    categoryPopularityRaw: 0.80,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 40,
    ageDays: 1200,
    daysSinceFreshEvidence: 8,
    evidence: evidence.high,
    latitude: 59.3128,
    longitude: 18.0842,
    engagement: { searchImpressions: 3100, profileViews: 920, mapMarkerClicks: 560, saves: 340, directionRequests: 210, confirmedVisits: 150, repeatVisits: 82, recommendations: 60, recentSaves: 105 },
    x: 58,
    y: 74,
  },
  {
    id: 28,
    name: "Ramblas Tapas",
    kind: "Restaurant",
    cuisine: "spanish",
    area: "Södermalm",
    address: "Långholmsgatan 3",
    note: "Vibrant independent Spanish tapas restaurant near Hornstull serving authentic jamón ibérico, croquetas, patatas bravas, and sangria.",
    tags: ["Spanish", "Tapas", "Sangria", "Authentic", "Independent"],
    evidenceLabel: "Specialist guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 940,
    reviewCount: 1250,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.82,
    localPopularityPercentile: 0,
    priceLevel: 2,
    mainstreamExposure: 52,
    ageDays: 3200,
    daysSinceFreshEvidence: 14,
    evidence: evidence.high,
    latitude: 59.3161,
    longitude: 18.0345,
    engagement: { searchImpressions: 3400, profileViews: 1100, mapMarkerClicks: 670, saves: 420, directionRequests: 260, confirmedVisits: 180, repeatVisits: 90, recommendations: 72, recentSaves: 125 },
    x: 28,
    y: 68,
  },
  {
    id: 29,
    name: "Boqueria",
    kind: "Restaurant",
    cuisine: "spanish",
    area: "Norrmalm",
    address: "Jakobsbergsgatan 17",
    note: "Bustling Spanish market hall restaurant serving artisanal tapas, seafood paella, and Spanish wines.",
    tags: ["Spanish", "Tapas", "Paella", "Market hall", "Independent"],
    evidenceLabel: "White Guide · OSM",
    ratingAverage: 4.5,
    reliableRatingCount: 2400,
    reviewCount: 3200,
    categoryMeanRating: 4.25,
    categoryPopularityRaw: 0.89,
    localPopularityPercentile: 0,
    priceLevel: 3,
    mainstreamExposure: 76,
    ageDays: 4200,
    daysSinceFreshEvidence: 7,
    evidence: evidence.high,
    latitude: 59.3345,
    longitude: 18.0698,
    engagement: { searchImpressions: 6800, profileViews: 2100, mapMarkerClicks: 1300, saves: 780, directionRequests: 510, confirmedVisits: 360, repeatVisits: 180, recommendations: 145, recentSaves: 240 },
    x: 52,
    y: 32,
  },
]);
