"""Cross-fitted residual model for platform underexposure research.

The model predicts a platform-typical rating from structural/exposure features.
Every published prediction is generated by a model that did not train on that
venue. Positive residuals indicate algorithmic surprise, not food quality.

Commercial-platform fields handled here are quarantined research inputs. They
must not be copied into Motkarta's intrinsic quality or evidence scores.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
from sklearn.model_selection import GroupKFold, KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


MODEL_VERSION = "discovery-hgbr-spatial-oof-v1"
NUMERIC = ["log_review_count", "price_level", "latitude", "longitude"]
CATEGORICAL = ["category", "cuisine", "district", "chain_status"]
REQUIRED = ["platform_rating", "review_count", "price_level", "latitude", "longitude", *CATEGORICAL]


@dataclass(frozen=True)
class DiscoveryDiagnostics:
    model_version: str
    folds: int
    validation_strategy: str
    mean_absolute_error: float
    root_mean_squared_error: float
    nominal_interval_coverage: float
    observed_interval_coverage: float


def fit_discovery_model(
    frame: pd.DataFrame,
    *,
    max_folds: int = 5,
    interval_coverage: float = 0.9,
    random_state: int = 42,
) -> pd.DataFrame:
    """Return leakage-resistant underexposure candidates with OOF predictions.

    Spatial groups are held out together whenever the dataset spans at least two
    grid cells. A deterministic shuffled K-fold split is the fallback for small
    or spatially concentrated fixtures.
    """
    data = _prepare_input(frame)
    if len(data) < 4:
        raise ValueError("Discovery modelling requires at least four complete venue rows.")
    if max_folds < 2:
        raise ValueError("max_folds must be at least 2.")
    if not 0.5 <= interval_coverage < 1:
        raise ValueError("interval_coverage must be between 0.5 and 1.0.")

    features = NUMERIC + CATEGORICAL
    splits, strategy = _validation_splits(data, max_folds=max_folds, random_state=random_state)
    predictions = np.full(len(data), np.nan, dtype=float)
    fold_ids = np.full(len(data), -1, dtype=int)

    for fold_id, (train_idx, test_idx) in enumerate(splits):
        model = _build_pipeline(random_state=random_state + fold_id)
        model.fit(data.iloc[train_idx][features], data.iloc[train_idx]["platform_rating"])
        predictions[test_idx] = model.predict(data.iloc[test_idx][features])
        fold_ids[test_idx] = fold_id

    if np.isnan(predictions).any() or (fold_ids < 0).any():
        raise RuntimeError("Cross-validation did not produce exactly one prediction per venue.")

    data["expected_platform_rating_oof"] = np.clip(predictions, 1.0, 5.0)
    # Compatibility alias: this is now always the out-of-fold estimate.
    data["expected_platform_rating"] = data["expected_platform_rating_oof"]
    data["rating_residual"] = data["platform_rating"] - data["expected_platform_rating_oof"]

    # Cross-fitted error band calibrated from other folds' OOF errors. This is
    # intentionally conservative at the candidate layer.
    interval_radii = _cross_fitted_error_radii(
        data["rating_residual"].to_numpy(), fold_ids, interval_coverage
    )
    data["residual_interval_radius"] = interval_radii
    data["residual_lower_bound"] = data["rating_residual"] - interval_radii
    data["residual_upper_bound"] = data["rating_residual"] + interval_radii
    data["underexposure_confidence"] = _empirical_underexposure_confidence(
        data["rating_residual"].to_numpy(), interval_radii
    )
    data["discovery_percentile"] = data["rating_residual"].rank(pct=True).round(4)
    data["ml_fold_id"] = fold_ids
    data["ml_validation_strategy"] = strategy
    data["ml_model_version"] = MODEL_VERSION
    data["ml_lifecycle_state"] = "candidate"
    data["ml_allowed_use"] = "Assistant proposal only; evidence gates decide user-facing hidden-gem confidence."
    data["source_gap_flags"] = data.apply(source_gap_flags, axis=1)
    data["ml_candidate_reason"] = data.apply(ml_candidate_reason, axis=1)

    diagnostics = DiscoveryDiagnostics(
        model_version=MODEL_VERSION,
        folds=len(splits),
        validation_strategy=strategy,
        mean_absolute_error=round(float(mean_absolute_error(data["platform_rating"], predictions)), 4),
        root_mean_squared_error=round(float(root_mean_squared_error(data["platform_rating"], predictions)), 4),
        nominal_interval_coverage=interval_coverage,
        observed_interval_coverage=round(
            float(np.mean(np.abs(data["rating_residual"].to_numpy()) <= interval_radii)), 4
        ),
    )
    data.attrs["diagnostics"] = diagnostics
    return data.sort_values("rating_residual", ascending=False)


def _prepare_input(frame: pd.DataFrame) -> pd.DataFrame:
    missing = [column for column in REQUIRED if column not in frame.columns]
    if missing:
        raise ValueError(f"Missing required discovery-model columns: {', '.join(missing)}")

    data = frame.copy().reset_index(drop=True)
    data["platform_rating"] = pd.to_numeric(data["platform_rating"], errors="coerce")
    if data["platform_rating"].isna().any():
        raise ValueError("platform_rating must be numeric and non-null for every training row.")
    if not data["platform_rating"].between(1, 5).all():
        raise ValueError("platform_rating values must be between 1 and 5.")
    data["log_review_count"] = np.log1p(pd.to_numeric(data["review_count"], errors="coerce").clip(lower=0))
    return data


def _build_pipeline(*, random_state: int) -> Pipeline:
    preparation = ColumnTransformer(
        [
            ("numeric", SimpleImputer(strategy="median"), NUMERIC),
            (
                "category",
                Pipeline(
                    [
                        ("impute", SimpleImputer(strategy="most_frequent")),
                        ("encode", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
                    ]
                ),
                CATEGORICAL,
            ),
        ]
    )
    return Pipeline(
        [
            ("prepare", preparation),
            (
                "model",
                HistGradientBoostingRegressor(
                    max_iter=200,
                    learning_rate=0.06,
                    l2_regularization=0.1,
                    random_state=random_state,
                ),
            ),
        ]
    )


def _validation_splits(
    data: pd.DataFrame, *, max_folds: int, random_state: int
) -> tuple[list[tuple[np.ndarray, np.ndarray]], str]:
    # Roughly 1.1 km north/south in Stockholm. The longitude cell is widened to
    # compensate for convergence at Stockholm's latitude.
    lat_cell = np.floor(pd.to_numeric(data["latitude"], errors="coerce").fillna(0) / 0.01)
    lon_cell = np.floor(pd.to_numeric(data["longitude"], errors="coerce").fillna(0) / 0.02)
    groups = lat_cell.astype(str) + ":" + lon_cell.astype(str)
    group_count = int(groups.nunique())

    if group_count >= 2:
        folds = min(max_folds, group_count)
        splitter = GroupKFold(n_splits=folds)
        return list(splitter.split(data, groups=groups)), f"spatial_group_{folds}_fold"

    folds = min(max_folds, len(data))
    splitter = KFold(n_splits=folds, shuffle=True, random_state=random_state)
    return list(splitter.split(data)), f"shuffled_{folds}_fold_fallback"


def _cross_fitted_error_radii(
    residuals: np.ndarray, fold_ids: np.ndarray, coverage: float
) -> np.ndarray:
    """Calibrate each fold from other folds' OOF errors.

    Excluding the scored fold keeps its outcomes out of its own uncertainty
    radius. This is an empirical cross-fitted error band, not a causal interval.
    """
    absolute_errors = np.abs(residuals)
    radii = np.zeros(len(residuals), dtype=float)
    for fold_id in np.unique(fold_ids):
        test_mask = fold_ids == fold_id
        calibration_errors = absolute_errors[~test_mask]
        if len(calibration_errors) == 0:
            calibration_errors = absolute_errors
        # "higher" avoids interpolating an artificially narrow safety interval.
        radii[test_mask] = float(np.quantile(calibration_errors, coverage, method="higher"))
    return radii


def _empirical_underexposure_confidence(residuals: np.ndarray, radii: np.ndarray) -> np.ndarray:
    safe_radii = np.where(radii > 0, radii, 1.0)
    # A monotonic, bounded confidence transform. It is an empirical candidate
    # confidence—not a calibrated probability of food quality.
    confidence = 1 / (1 + np.exp(-residuals / safe_radii * 3))
    confidence = np.where((radii <= 0) & (residuals > 0), 1.0, confidence)
    confidence = np.where((radii <= 0) & (residuals <= 0), 0.0, confidence)
    return np.round(confidence, 4)


def source_gap_flags(row: pd.Series) -> str:
    gaps = []
    evidence_count = optional_float(row.get("independent_evidence_count"), default=0)
    if evidence_count < 2:
        gaps.append("needs_two_independent_evidence_signals")
    if not truthy(row.get("current_existence_verified")) and not row.get("latest_verified_date"):
        gaps.append("needs_current_existence_check")
    if not truthy(row.get("distinctiveness_verified")):
        cuisine = str(row.get("cuisine") or "").lower()
        category = str(row.get("category") or "").lower()
        if cuisine in {"", "general", "restaurant", "cafe", "coffee"} or category in {"", "restaurant", "cafe"}:
            gaps.append("needs_distinctiveness_reason")
    return ";".join(gaps) or "no_obvious_source_gap"


def ml_candidate_reason(row: pd.Series) -> str:
    return (
        f"Out-of-fold residual surprise {row['rating_residual']:.3f} "
        f"(lower bound {row['residual_lower_bound']:.3f}) at percentile "
        f"{row['discovery_percentile']:.4f}; review gaps before promotion: "
        f"{row['source_gap_flags']}."
    )


def optional_float(value: object, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def truthy(value: object) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_csv")
    parser.add_argument("--output", default="data/stockholm_discovery_scores.csv")
    parser.add_argument("--max-folds", type=int, default=5)
    parser.add_argument("--interval-coverage", type=float, default=0.9)
    args = parser.parse_args()
    result = fit_discovery_model(
        pd.read_csv(args.input_csv),
        max_folds=args.max_folds,
        interval_coverage=args.interval_coverage,
    )
    result.to_csv(args.output, index=False)
    diagnostics = result.attrs["diagnostics"]
    print(f"Saved discovery analysis to {args.output}")
    print(
        f"{diagnostics.model_version}: {diagnostics.validation_strategy}; "
        f"MAE={diagnostics.mean_absolute_error:.4f}; RMSE={diagnostics.root_mean_squared_error:.4f}"
    )


if __name__ == "__main__":
    main()
